# Generated by Django 5.1.3 on 2024-12-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
