# Generated by Django 5.1.3 on 2024-12-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active_customers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_contract',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lead',
            new_name='lead',
        ),
    ]
