# Generated by Django 5.1.3 on 2024-12-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ads_company_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=15, unique=True)),
                ("customer_email", models.EmailField(max_length=100, unique=True)),
                (
                    "ads_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads_company_app.advertise",
                    ),
                ),
            ],
        ),
    ]
