# Generated by Django 5.1.3 on 2024-12-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads_company_app", "0001_initial"),
        ("potential_customers_app", "0003_alter_leads_ads_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="ads_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ads_company_app.advertise",
            ),
        ),
    ]
